---
- name: "change /etc/hosts"
  lineinfile:
    path: "/etc/hosts"
    line: "{{ansible_default_ipv4['address']}}  {{ansible_hostname}}    {{ansible_fqdn}}    pvelocalhost"

- name: "change /etc/hosts (2/2)"
  lineinfile:
    path: "/etc/hosts"
    regexp: "127.0.1.1"
    #    regexp: '^127\.0\.1\.1\.\t'
    state: absent


- name: add proxmox repository key
  apt_key:
    url: "http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/proxmox-ve-release-5.x.gpg

- name: add proxmox repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve stretch pve-no-subscription
    state: present
    filename: pve-install-repo.list

- name: update apt repo
  apt:
    upgrade: dist
    update_cache: yes

- name: install proxmox
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - proxmox-ve
    - postfix
    - open-iscsi
